export type User = {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  status: "online" | "offline";
  type: "doctor" | "patient";
};

export const users: User[] = [
  {
    id: 0,
    email: "raffaele.ciavarella@gmail.com",
    firstName: "Raffaele",
    lastName: "Ciavarella",
    status: "online",
    type: "doctor",
  },
  {
    id: 1,
    email: "federico.mainetti.gambera@gmail.com",
    firstName: "Federico",
    lastName: "Mainetti Gambera",
    status: "online",
    type: "patient",
  },
  {
    id: 2,
    email: "frodo.baggins@shiremail.com",
    firstName: "Frodo",
    lastName: "Baggins",
    status: "online",
    type: "patient",
  },
  {
    id: 3,
    email: "samwise.gamgee@shiremail.com",
    firstName: "Samwise",
    lastName: "Gamgee",
    status: "online",
    type: "patient",
  },
  {
    id: 4,
    email: "aragorn.elessar@gondormail.com",
    firstName: "Aragorn",
    lastName: "Elessar",
    status: "offline",
    type: "doctor",
  },
  {
    id: 5,
    email: "gandalf.grey@istariorder.org",
    firstName: "Gandalf",
    lastName: "The Grey",
    status: "online",
    type: "doctor",
  },
  {
    id: 6,
    email: "legolas.greenleaf@mirkwood.com",
    firstName: "Legolas",
    lastName: "Greenleaf",
    status: "offline",
    type: "doctor",
  },
  {
    id: 7,
    email: "gimli.sonofgloin@erebor.net",
    firstName: "Gimli",
    lastName: "Son of Glóin",
    status: "online",
    type: "patient",
  },
  {
    id: 8,
    email: "boromir.ofgondor@gondor.net",
    firstName: "Boromir",
    lastName: "Of Gondor",
    status: "offline",
    type: "patient",
  },
  {
    id: 9,
    email: "arwen.undomiel@rivendell.com",
    firstName: "Arwen",
    lastName: "Undómiel",
    status: "online",
    type: "doctor",
  },
  {
    id: 10,
    email: "galadriel.lothlorien@lothlorien.org",
    firstName: "Galadriel",
    lastName: "of Lothlórien",
    status: "offline",
    type: "doctor",
  },
  {
    id: 11,
    email: "saruman.white@isengard.com",
    firstName: "Saruman",
    lastName: "The White",
    status: "offline",
    type: "doctor",
  },
  {
    id: 12,
    email: "peregrin.took@shiremail.com",
    firstName: "Peregrin",
    lastName: "Took",
    status: "online",
    type: "patient",
  },
  {
    id: 13,
    email: "meriadoc.brandybuck@shiremail.com",
    firstName: "Meriadoc",
    lastName: "Brandybuck",
    status: "online",
    type: "patient",
  },
  {
    id: 14,
    email: "bilbo.baggins@shiremail.com",
    firstName: "Bilbo",
    lastName: "Baggins",
    status: "offline",
    type: "patient",
  },
  {
    id: 15,
    email: "elrond.halfelven@rivendell.com",
    firstName: "Elrond",
    lastName: "Half-elven",
    status: "online",
    type: "doctor",
  },
  {
    id: 16,
    email: "theoden.rohan@rohanmail.com",
    firstName: "Théoden",
    lastName: "King of Rohan",
    status: "offline",
    type: "patient",
  },
  {
    id: 17,
    email: "eowyn.shieldmaiden@rohanmail.com",
    firstName: "Éowyn",
    lastName: "Shieldmaiden",
    status: "online",
    type: "doctor",
  },
  {
    id: 18,
    email: "eomer.rohan@rohanmail.com",
    firstName: "Éomer",
    lastName: "Of Rohan",
    status: "offline",
    type: "doctor",
  },
  {
    id: 19,
    email: "treebeard.ent@fangornforest.com",
    firstName: "Treebeard",
    lastName: "The Ent",
    status: "online",
    type: "patient",
  },
  {
    id: 20,
    email: "haldir.lorien@lothlorien.org",
    firstName: "Haldir",
    lastName: "Of Lothlórien",
    status: "offline",
    type: "doctor",
  },
  {
    id: 21,
    email: "gollum.smeagol@mistymountains.com",
    firstName: "Gollum",
    lastName: "Sméagol",
    status: "online",
    type: "patient",
  },
  {
    id: 22,
    email: "denethor.gondor@gondormail.com",
    firstName: "Denethor",
    lastName: "Of Gondor",
    status: "offline",
    type: "doctor",
  },
  {
    id: 23,
    email: "faramir.gondor@gondormail.com",
    firstName: "Faramir",
    lastName: "Of Gondor",
    status: "online",
    type: "doctor",
  },
  {
    id: 24,
    email: "grima.wormtongue@isengard.com",
    firstName: "Gríma",
    lastName: "Wormtongue",
    status: "offline",
    type: "patient",
  },
  {
    id: 25,
    email: "radagast.brown@istariorder.org",
    firstName: "Radagast",
    lastName: "The Brown",
    status: "online",
    type: "doctor",
  },
  {
    id: 26,
    email: "sauron.darklord@mordor.net",
    firstName: "Sauron",
    lastName: "The Dark Lord",
    status: "offline",
    type: "doctor",
  }
] as const;
